### PR TITLE
Clicking Recommended copies values down! Closes #286

### LINKED ISSUE #286: Feature: Tap suggested Bolus to copy it down to the next line
I'd like to (attempt) my first Swift PR and do this. When I get a suggested bolus, I'd like to Tap the suggestion to have it copied down into the text box on the next line, then you tap deliver.

It's small, but it's a nice little improvement with minimal (no?) safety implications.

### PR DESCRIPTION
**Pull request by shanselman**
Clicking Recommended copies values down! Closes #286

Hope I did it write, I’m not a swift person.

Crap..now I messed it up with Git. I lost the work...looking...

### CODE REVIEW

**Comment by ps2** [comment]
I think something was missed. I don't see the code to perform the feature change.

Also, there are changes here that are just your personalizations.

**Comment by shanselman** [comment]
Yes, I know, sorry @ps2. I was there, looked great, then I was tidying up locally with GitDeskop and it kept the PR with this context and now my local crap is here. I'm looking now...:( Sorry

**Comment by ps2** [comment]
No worries! 👍

Let me know when you want me to take another look.

**Comment by shanselman** [comment]
If you have a second, they are here now above your comment @ps2 but I don't see how to get rid of the first commits

**Comment by shanselman** [comment]
UGH. Close me.

**Pull request closed without merging**
