### PR TITLE
Add patch to handle invalid archs better (fixes #1117)

### LINKED ISSUE #1117: Can't build IPA with latest Dev with Xcode 11-2.
I am using the latest Dev and Xcode 11-2. I can build Loop for my phone, but when I try to Archive to make an Ad-Hoc IPA, it says IPA Processing Failed. It seems like part of MiniMed Plugin is having an issue. I see this in the logs:

2019-09-20 02:21:44 +0000 Scanning IPA...
2019-09-20 02:21:46 +0000 Assertion failed: Expected 2 archs in otool output:
/var/folders/8k/7c4406k90ds6vhz585ljmx140000gp/T/IDEDistributionOptionThinning.~~~kZyTmZ/Payload/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin:
Mach header
magic cputype cpusubtype caps filetype ncmds sizeofcmds flags
MH_MAGIC_64 X86_64 ALL 0x00 DYLIB 24 3136 NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
Load command 0

### PR DESCRIPTION
**Pull request by dekimsey**
This is an updated apply of PR #1126 which addresses the issue reported
in #1117

Note this has been an original issue was reported Sept 19. I myself, applied it locally with a minor tweak to support updated rileylink version for v2.0 in January and now again on v2.2.

Hopefully this helps others trying to sign the package.

### CODE REVIEW

**Comment by dekimsey** [comment]
My best understanding of the issue and solution is in the comments of [#1117, here](https://github.com/LoopKit/Loop/issues/1117#issuecomment-570341063).

**Comment by earnshavian** [comment]
I can confirm this fixes archiving builds and leaves dev builds intact on xcode 11.5.  My only suggestion would be to add the new script as a file in Xcode so it shows in the scripts folder with the others. Great work!

**Comment by dekimsey** [comment]
I've updated this PR to be based on the latest release v2.2.4_xcode12. I did have to add an additional flag to enable active archs only.

**Comment by gestrich** [comment]
Anyone have luck creating an archive with this branch or any other branch lately? If so, can you let me know what Xcode version and branch you are using? I've been attempting with this branch, master, dev with various versions of of Xcode (12.1, 12.4) and keep hitting error related to Lipo. My goal is to create an ipa to upload to AppCenter. I can share more details on the errors but first wanted to see what the configuration is for anyone that can successfully create an archive.

**Comment by gestrich** [comment]
Update: I've added a PR for master which seems to overcome the issues I was having: [1489](https://github.com/LoopKit/Loop/pull/1489/commits/4a0839c1bf71fedbe7a449c7db21b728409aa7e0)

**Comment by ps2** [comment]
I believe the archive build and upload to TestFlight is working fine in the workspace build. The carthage based build is no longer working, and we are dropping that from the documentation.

**Pull request closed without merging**
