### PR TITLE
DarkMode

### PR DESCRIPTION
**Pull request by clvsjr9**
Merge DarkMode option to Loop app (not Loopkit)

### CODE REVIEW

**Comment by ps2** [comment]
Could you get this into a buildable state? The build has a number of errors.

**Comment by clvsjr9** [comment]
I tried to compile the application and there were several compilation errors not related to the DarkMode functionality. Following are figures with error messages. I believe that some modification in Loopkit is contributing to the appearance of these errors. Example: LoopNotificationCategory with no members present and others more as messages in the figure. The so called carthage update completes successfully (see fig as well).

CompilerErrs

Carthage update (without errors):

AllSchemesOK

No functionality of the Loopkit project was changed by the implementation of DarkMode. It stayed exclusive in the app loop. How can I continue?

**Comment by cyoung1024** [comment]
Double check your Cartfile, it looks like it's pulling info from jojo

**Comment by clvsjr9** [comment]
Thanks @cyoung1024 for Cartfile orientation. I checked and it's OK.

I downloaded again the original files for dev branch of Loop app and applied manually the DarkMode coding on them. All code marked with: //DarkMode

Now the project compiled OK. Follow some pics from simulator:

DarkModeOn

DarkModeOff

DarkStatusView

@ps2, I committed and pushed the same fork again. When possible take a look please.

Thanks in advance for all.

**Comment by ps2** [comment]
Thanks. Looks like the light grey bands should be made black.  I'll check it out more fully later.

**Comment by ps2** [comment]
Looks like a good start!  The bolus and carb entry screens are not updated, as well as many of the settings screens. You would need to address some of these with a PR to LoopKit.

**Comment by clvsjr9** [comment]
@ps2, created: DarkMode - LoopKit #278

**Comment by mpangburn** [comment]
Neat. There have been rumors of a system-wide dark mode with iOS 13, and if the API is similar to the one that shipped with macOS last year, we may want to wait until WWDC to build theming architecture.

**Comment by clvsjr9** [comment]
Let's hope the rumor will confirm ....
Let's wait for beta iOS 13 to see ...

**Comment by chadharper0131** [comment]
what about just using the invert colors option, or the "modified" invert colors option??? That kinda gives you a dark mode.~~~>  i used to always leave that on at nighttime - and it definitely made life much easier on my eyeballs!!! .. I havent seen or used that option since i had an iphone 6S+, but im sure it still exists, somehow someway...

**Comment by clvsjr9** [comment]
Could be done follow these steps:

How to turn on Smart Invert on your iPhone or iPad

Open Settings on your iPhone or iPad.
Tap General.
Tap Accessibility.
Tap Display Accommodations.
Tap Invert Colors.
Tap the switch next to Smart Invert to flip it to the 'on' position.

I prefer the app's exclusive internal programming...

**Comment by scottleibrand** [comment]
If you want to regularly use Smart Invert as a workaround, you probably also would want to set it up as an accessibility shortcut so it can be activated and deactivated by triple-click.

**Comment by loudestnoise** [comment]
The Mac rumor mill does seem to indicate that there will be a Dark Mode in iOS 13. We should find out more on Monday after the WWDC keynote.

https://9to5mac.com/2019/05/28/ios-13-screenshots-dark-mode-more/

https://www.macrumors.com/roundup/ios-13/#dark_mode

**Comment by ps2** [comment]
A Dark Mode update using built-in iOS support is in the works, and will be submitted as a new PR.

**Pull request closed without merging**
