### PR TITLE
Jojo spike with DarkMode

### PR DESCRIPTION
**Pull request by clvsjr9**
I would like to share a small contribution made by me in the Loop app (not LoopKit) containing possibility of customization of DarkMode Theme through user selection if he/she wishes in the settings menu. All customization of the code has been marked with the comment: //DarkMode (see the figure indicating the custom files). If you consider interesting and, if you want, incorporate into your own branches and feel free to study and download it at: https://github.com/clvsjr9/1.10.0dev-jojo-spike-DarkMode

blackTheme

whiteTheme

ModifiedFiles

Example of Main Status Page with DarkMode:

StatusPage

### CODE REVIEW

**Comment by ps2** [comment]
Very interesting. Could you post screen shots of the main status page? This would need to be rebased to dev for me to take a look at.

**Comment by loudestnoise** [comment]
Oooh @clvsjr9 rebase with `dev` so Pete can take a look. Dark Mode FTW!

**Comment by cyoung1024** [comment]
Love this idea. Everything I own is dark mode if it’s an option ! Can’t wait to take a closer look.

**Comment by clvsjr9** [comment]
@loudestnoise how to rebase with dev? I have no experience with this feature. Could you help me?

**Comment by ps2** [comment]
By 'rebase', I don't mean the git rebase command exactly. I just mean having your changes as a diff from the loop main dev branch. You can get there many ways; starting with a copy of Loop dev, and copying your changes over, or taking the commit diffs from when you checked in your changes, and applying them to dev manually, or trying to cherry pick them, etc..  Which one is best depends on your familiarity with git.  There are lots of tutorials out on the web if you want to learn about rebase, cherry-pick or managing diffs manually.

**Comment by clvsjr9** [comment]
@ps2 all diffs applied and pushed  at https://github.com/clvsjr9/Loop-dev

**Comment by ps2** [comment]
Could you submit your cleaned up changes as a PR now?  It looks like the branch you mention in your last comment is in a repo that is not actually a fork of the Loop app. You'll have to push that branch to an actual fork of LoopKit/Loop, to submit a PR.

**Comment by clvsjr9** [comment]
My last comment used this branch to be done: https://github.com/LoopKit/Loop/tree/dev
Is it correct branch?

**Comment by ps2** [comment]
Yes, that is the branch you should base it off. But to submit it as a PR, you need to push it to a repo that is a github fork of https://github.com/LoopKit/Loop

**Comment by clvsjr9** [comment]
Pushed to a github fork of https://github.com/LoopKit/Loop

Please check if the action indicated in the official branch dev was correctly performed. Thank you.

PushedDarkMode

**Comment by ps2** [comment]
What is the URL of this new fork?  You need to create a new PR from that fork.

**Comment by clvsjr9** [comment]
The URL is: https://github.com/clvsjr9/Loop.git

PR DarkMode #959

**Comment by ps2** [comment]
Thanks, I see the new PR, and it looks like a clean patch, will check it out.

**Pull request closed without merging**
