### PR TITLE
Add dashed line in graphs to mark the current time.

### PR DESCRIPTION
**Pull request by lgruen**
Example: img_1298

### CODE REVIEW

**Comment by dabear** [comment]
Great! This is something I've wanted for a long time

**Comment by francescaneri** [comment]
@ ps2 what do you think?

**Comment by ps2** [comment]
Looks nice! The bg graph might not need the dashed line, but it may make sense to keep it there for consistency.  On the other (lower) graphs, I often use the touch readout to see where the current time lines up.

**Comment by Kdisimone** [comment]
@ps2 for old BGs, the line stays with the last BG reported, until a new BG comes in.

**Comment by ps2** [comment]
The more I think about this and look at it the more the vertical line seems unnecessary.  The top graph is very obvious where the forecast begins. For the insuliin and carb graphs, the values are always predictions, and thus there isn't the same distinction between current and predicted values.  For insulin delivery the future part isn't really a prediction either, but a display of the duration of the currently set basal.

**Comment by marcusfpereira** [comment]
I was about to open a feature request for this line, I miss it a lot. Mainly on the Insulin Delivery graph.

**Pull request closed without merging**
