### PR TITLE
Added new strings and translations (Norwegian Bokmål)

### PR DESCRIPTION
**Pull request by jannyg**
Added some new strings and translations missing. There's still a lot missing, but it's a start I guess. I'm not a programmer and not familiar with Swift, but it seem to me like there are some strings not defined with "NSLocalizedString"?

### CODE REVIEW

**Comment by Jon-b-m** [comment]
If adding new strings you need to add the source strings and the strings for all languages. Much better to let Crowding handle the strings sync.

**Comment by Joerg-Schoemer** [comment]
> Upload the source strings and nb.lproj to Crowdin.

can you provide the complete URL to the crowdin project.

**Comment by jannyg** [comment]
Hi @Jon-b-m , could you please point us in the right direction for the Crowdin project?

**Comment by Jon-b-m** [comment]
> Hi @Jon-b-m , could you please point us in the right direction for the Crowdin project? 

https://crowdin.com/project/looptranslation

This is not my Crowdin project however, and I don't know if it's still used. If you don't find the strings there you can contact the owner of the Crowdin project.

**Comment by jannyg** [comment]
The strings are missing from the project and I have not received a response sent to the owner 4th of May. Seems abandoned.

**Comment by ps2** [comment]
Thanks!

**Pull request merged**
