### PR TITLE
Show 12h or 24h time on chart x-axis depending on locale

### PR DESCRIPTION
**Pull request by ps2**
Updated version of #919. Thanks @reelman!

### CODE REVIEW

**Comment by reelman** [comment]
Thank you for doing it in right way 🙂👍

**Comment by eszcloud** [comment]
Does "Show 12h or 24h time on chart x-axis depending on locale" mean that the x-axis format will change if we travel to a new locale (e.g. US to Europe) and update the timezone to a local one?

**Comment by ps2** [comment]
No, only if you change your time format in settings or change the language (locale) on your phone.

**Comment by eszcloud** [comment]
Got it. Thanks!

**Pull request merged**
