### PR TITLE
Do not display stale glucose data

### PR DESCRIPTION
**Pull request by erikdi**
Currently the UI sometimes keeps display the last Glucose value, which can be in the best case confusing, in the worst case dangerous.  Blank it out if the data is older than 15 minutes.

### CODE REVIEW

**Comment by diggabyte** [comment]
Could this perhaps be addressed through a new `sensorAlertState` which indicates the value is stale, like ⏱or ⎋ or something, rather than blanking it out completely?

**Comment by PieterGit** [comment]
I would follow @diggabyte solution of adding an icon. But I would also let the loop implementation look a bit like Nightscout's implementation. Nightscout has a striketrhough and uses grey font color. For example it looks like:
image

**Comment by ps2** [comment]
If you (or anyone else) rebases this change and submits before I get to it, I can take a look at it; this is a needed change.

**Comment by diggabyte** [comment]
@ps2 are you fine with blanking it out? Or should we do an icon or text treatment to this?

**Pull request closed without merging**
