### PR TITLE
Complete ِArabic translations

### PR DESCRIPTION
**Pull request by abutmim**

### CODE REVIEW

**Comment by ps2** [comment]
Thanks, @abutmim. There are other repos you may want to look at tackling, that contain strings used in Loop as well: 
* https://github.com/LoopKit/LoopKit
* https://github.com/ps2/rileylink_ios
* https://github.com/LoopKit/CGMBLEKit
* https://github.com/LoopKit/dexcom-share-client-swift
* https://github.com/LoopKit/G4ShareSpy

**Comment by ps2** [comment]
@abutmim Thanks for these changes, but this branch was submitted against master and not dev. You need to do your work from dev, and submit it as a PR to merge back into dev.

**Comment by abutmim** [comment]
> 
> 
> Thanks, @abutmim. There are other repos you may want to look at tackling, that contain strings used in Loop as well:
> 
>     * https://github.com/LoopKit/LoopKit
> 
>     * https://github.com/ps2/rileylink_ios
> 
>     * https://github.com/LoopKit/CGMBLEKit
> 
>     * https://github.com/LoopKit/dexcom-share-client-swift
> 
>     * https://github.com/LoopKit/G4ShareSpy

I am working  in it 

Thanks

**Comment by ps2** [comment]
@abutmim Yes. I was able to rebase your last changes fine, but these ones have conflicts, so you'll need to apply these changes to dev in a new workspace, and submit a new PR.

**Comment by abutmim** [comment]
> 
> 
> @abutmim Yes. I was able to rebase your last changes fine, but these ones have conflicts, so you'll need to apply these changes to dev in a new workspace, and submit a new PR.

Thanks

I will

**Comment by ps2** [comment]
It's probably best to contribute your Arabic translations for Loop through this project now: https://github.com/LoopTranslation/LoopTranslation/wiki/Getting-started

**Pull request closed without merging**
