### PR TITLE
display - for HUD CGM when value is >15 min old

### PR DESCRIPTION
**Pull request by Kdisimone**
fresh base for @erikdi work at https://github.com/LoopKit/Loop/pull/709

### CODE REVIEW

**Comment by Kdisimone** [comment]
IMG_8069

**Comment by Kdisimone** [comment]
or there's the emoji option which might be nice?

IMG_8070

**Comment by ps2** [comment]
The accessory notice (the little grey circle on the upper right of the HUD) is showing a weird tiny cloud?  Old bg should probably be a notice state, so warning/yellow, with an exclamation.

**Comment by ps2** [comment]
Haha. Funny. Maybe the missing glucose emoji should be kept a nice custom code change hack for people who want that. ;)

**Comment by Kdisimone** [comment]
> The accessory notice (the little grey circle on the upper right of the HUD) is showing a weird tiny cloud? Old bg should probably be a notice state, so warning/yellow, with an exclamation.

Eventually switched (see above with the emoji version). that cloud icon has been oddly buggy (in terms of how it is displayed kinda truncated) for awhile, I've noticed.

**Comment by Kdisimone** [comment]
I'd be happy to put it in the customizations of loopdocs, good idea

**Pull request merged**
