### PR TITLE
Upload carbs-on-board to Nightscout

### PR DESCRIPTION
**Pull request by mddub**
For https://github.com/mddub/urchin-cgm/pull/50.

I would appreciate it if someone else (@ps2?) could test this before I merge. You should see something like this in `/api/v1/devicestatus.json?find[loop][$exists]=1`:

```
{
  "loop": {
    "cob": {
      "timestamp": "2016-10-20T23:40:00Z",
      "cob": 18.2929316872428
    }, ...
  }, ...
}

### CODE REVIEW

**Comment by ps2** [comment]
I see cob uploading to NS, and I see it showing in urchin!  Very nice!  It's not showing in the COB plugin in NS, but I believe that is just that NS needs to be updated to look there for Loop cob.

**Comment by ps2** [comment]
Just waiting to see it update.  I reviewed the code and couldn't see anything to improve upon.  Will approve once I see the update.

**Comment by ps2** [comment]
I do see some occasional issue in NS about 'cob' being undefined, but that's probably more NS issues to work through.

**Comment by mddub** [comment]
Awesome! Thanks for reviewing and helping test!

**Pull request merged**
