### PR TITLE
Omnipod Integration

### PR DESCRIPTION
**Pull request by ps2**
This PR integrates the [Omnipod PumpManager](https://github.com/ps2/rileylink_ios/pull/492) into Loop

### CODE REVIEW

**Comment by ps2** [comment]
This will not be merged, but will remain as is for the time being as it is in wide use in its current state.  The omnipod-testing-integrate branch is being used to integrate other fixes and changes from dev, and will be the branch that will eventually be merged in to dev.  Omnipod fixes will then go into dev, for an eventual release version.

**Comment by Aragorn450** [comment]
I just noticed the omnipod-testing-integrate branch. Should I use that for building for the OmniPod or the normal omnipod-testing branch?

**Comment by Kdisimone** [comment]
@Aragorn450 you should follow docs and use the branch stated in there. Omnipod-testing.

**Comment by Aragorn450** [comment]
@Kdisimone OK, I'll use that one. From a development standpoint, what is the integration branch for? I'm just starting with Loop but have a bit of app development background and might be able to contribute some.

**Comment by Kdisimone** [comment]
@Aragorn450 did you see Pete’s comment above? He explained the purpose of the branch

**Comment by ps2** [comment]
If you have omnipod specific contributions, they should be based against omnipod-testing-integrate. Otherwise, the main loop dev branch.

**Pull request closed without merging**
