### PR TITLE
Override ns upload

### PR DESCRIPTION
**Pull request by Kdisimone**

### CODE REVIEW

**Comment by francescaneri** [comment]
thanks @Kdisimone !

**Comment by francescaneri** [comment]
@jasoncalabrese  what could be the error?

**Comment by Kdisimone** [comment]
@francescaneri what error are you talking about?  The Travis check? Ignore.

**Comment by francescaneri** [comment]
Schermata 2019-07-31 alle 17 40 57
@Kdisimone  I have this error in compiling

**Comment by ps2** [comment]
Implemented in #1064

**Pull request closed without merging**
