### PR TITLE
Modify saveWithoutBolus to save Carbs with no active pump

### PR DESCRIPTION
**Pull request by marionbarker**
Edited to add that I believe this fixes the problem reported in Issue #1633 Cannot Enter and Save Carbs when no pump configured.

~In response to Issue #1643 Duplicate carb entries can be saved:~

Add a saveWithoutBolusing function that does not have all the checks (like is bolus already running) that saveAndDeliver requires.

The new saveWithoutBolusing function has been tested in these cases:
* with CGM data, add carb entry, bolus recommended, modify to 0 U - saves carbs and dismisses screen
* missing BG data - tap carb entry:
  * enter FS data, add carb entry, bolus recommended, modify to 0 U - saves carbs and FS data 
* missing BG data - tap manual bolus entry:
  * enter FS data, bolus recommended, modify to 0 U - saves FS data 
* start a large bolus (on test phone)
  * add carb entry, bolus recommended, modify to 0 U - saves carbs and dismisses screen (while bolus is still continuing)

### CODE REVIEW

**Comment by marionbarker** [comment]
I could have sworn that I was able to reproduce this error yesterday (before this modification) by having the app delivering insulin when I added carbs and selected Save without Bolusing, but I could not make it fail today.

Perhaps the change proposed [here](https://github.com/Joerg-Schoemer/Loop/commit/89f4837f4be2617daa48c1837fd3cbc340231abc) should be selected instead of or in addition to.

**Comment by ps2** [comment]
Please describe the problem that this is fixing.

**Comment by marionbarker** [comment]
This was in response to [Issue 1643: Duplicate carb entries can be saved](https://github.com/LoopKit/Loop/issues/1643) which happened to me.  The issue is that sometimes `Save without Bolusing` does not work properly - it saves the carbs when you hit it but it continues to show the BolusEntryView screen and allowed me to tap Save without Bolusing again - and saved carbs again.

See also this [zulipchat post](https://loop.zulipchat.com/#narrow/stream/198661-ux/topic/update.20BolusEntryView/near/280815271)

I convinced myself I could reproduce it by starting a bolus and entering carbs and trying to `Save without Bolusing` while the first bolus was still going. 

The next day, I went back and tried to make issue 1643 happen again (with original dev, not with this code) and I could not reproduce it.

At that time, I looked at https://github.com/Joerg-Schoemer/Loop/commit/89f4837f4be2617daa48c1837fd3cbc340231abc and was not sure if that was the correct fix either.

I don't think the code is "wrong" but it may not be necessary. And it may not be sufficient to fix this bug.

**Comment by marionbarker** [comment]
While reviewing open issues, I came across Issue #1633 Cannot Enter and Save Carbs When There Isn't an Insulin Pump Added and Configured.

I believe that this PR solves that issue.
Use Case 1: No Pump Configured
* new Looper might be wanting to use Loop to make predictions while they are learning the interface and manually controlling a pump
* experienced Looper might be switching between insulin delivery methods, but needs to enter carbs in the interim to keep predictions accurate

Use Case 2: 
* Pod Looper is between pods and needs to enter carbs in the interim to keep predictions accurate

Graphic showing success when PR 1678 has been applied when between pods:

PR_1678_fix_SaveWithoutBolusing

**Comment by marionbarker** [comment]
If user wants to save carbs and enter BG without really attaching a pump they can add a simulator (if they want dosing suggestions) or add a pod and cancel at pairing if they just want to save carbs / BG.

**Pull request closed without merging**
