### PR TITLE
Update widgets for build with Xcode 15

### PR DESCRIPTION
**Pull request by Camji55**
Adds back Widget changes originally made for #2013 that were reserved to Xcode 15

### CODE REVIEW

**Comment by snics** [comment]
@Camji55 I had already fixed the backgrund and created a PR #2076. Should I delete my PR then?

**Comment by bfeinzimer** [comment]
I think this might be broken still, just updated to dev ver 3.3.0 (57) (Loop_dev-230930-1325) and still getting the widget error on ios 17.
Screenshot 2023-09-30 at 1 37 09 PM

**Comment by bfeinzimer** [comment]
nvm, I ran the build again and now the widget works. weird.

**Comment by thomasvargiu** [comment]
@ps2 Is it possible to cherrypick this on main branch and release the fix?

**Pull request merged**
