### PR TITLE
upload symbols to nightscout

### PR DESCRIPTION
**Pull request by CodeByMini**
This pull request allows the Lollipop, Taco and Pizza symbols to be automatically uploaded to Nightscout.
The reason for this is to have a quick view of what kind of carbs that were entered instead of having to hover over the treatment in Nightscout.

The code is kind of a work around and could definitely be improved, but it does the job.
A known bug is that if the user selects different food icons they will not be uploaded if the meal time is 2, 3 or 4 hours. It also has to be edited if the user has choosen different carb absoprtion times for .fast .medium. slow

I would love to see a more experienced programmer commit to this

### CODE REVIEW

**Comment by loyalchallenger** [comment]
This already happens on my nightscout. I can send you a screenshot.

**Comment by CaspianGeben** [comment]
> This already happens on my nightscout. I can send you a screenshot.

Show a screenshot on how you add carbs
This take the three symbols from the first screen and uploads that symbol. I am not using the symbols you can choose after selecting the plate.

**Comment by loyalchallenger** [comment]
There is no option for me to upload screenshots here. 

I’m not sure what symbols you’re using then. I’m using the symbols provided in loop. I choose them when I enter carbs and they show up in my nightscout.

**Comment by CaspianGeben** [comment]
> There is no option for me to upload screenshots here.
> 
> I’m not sure what symbols you’re using then. I’m using the symbols provided in loop. I choose them when I enter carbs and they show up in my nightscout.

If you use an apple watch do you see the symbols in nightscout then?

**Comment by CaspianGeben** [comment]
if you choose one of these three symbols (circled in red) without clicking the plate (crossed over) and choosing the same symbols from that meny, does that still show up in nightscout?
IMG_9891

**Comment by loyalchallenger** [comment]
I see what you’re saying. You want a default option to upload to nightscout. I do not use the Apple Watch.

**Comment by rolandet** [comment]
The symbols automatically upload for me with Loop v2.0.

**Comment by Nightfoxy** [comment]
Watch entries do not add the symbols.

**Comment by CaspianGeben** [comment]
> The symbols automatically upload for me with Loop v2.0.
> 
> A5898ADC-C505-49F3-8666-CC05C1574D27

Yes. because you choose them under the plate. if you just choose the lollipop, taco or pizza on the screenshot I posted you will not get the symbols to Nightscout

**Comment by ps2** [comment]
I believe this functionality is working in current Loop.

**Pull request closed without merging**
